export const cars = [
  {
    image: 'Imagem 32.png',
    name: 'Mini Cooper',
    year: '2021',
    type: 'Hatch compacto',
    engine: '1.8',
    size: '5',
  },
  {
    image: 'Imagem 16.png',
    name: 'Jeep Compass',
    year: '2021',
    type: 'SUV Médio',
    engine: '1.8',
    size: '7',
  },
  {
    image: 'Imagem 15.png',
    name: 'Duster',
    year: '2020',
    type: 'SUV Compacta',
    engine: '1.6',
    size: '5',
  },
  {
    image: 'Imagem 31.png',
    name: 'Partner',
    year: '2016',
    type: 'Utilitário',
    engine: '1.6',
    size: '2',
  },
  {
    image: 'Imagem 30.png',
    name: 'Fiorino',
    year: '2017',
    type: 'Utilitário leve',
    engine: '1.6',
    size: '2',
  },
  {
    image: 'Imagem 29.png',
    name: 'Doblo',
    year: '2018',
    type: 'Minivan',
    engine: '1.8',
    size: '7',
  },
  {
    image: 'Imagem 25.png',
    name: 'Toro',
    year: '2016',
    type: 'Picape média',
    engine: '1.6',
    size: '5',
  },
  {
    image: 'Imagem 9.png',
    name: 'Ford Ká',
    year: '2019',
    type: 'Sedan Compacto',
    engine: '1.0',
    size: '5',
  },
  {
    image: 'Imagem 27.png',
    name: 'Versa',
    year: '2019',
    type: 'Sedan médio',
    engine: '1.4',
    size: '5',
  },
  {
    image: 'Imagem 28.png',
    name: 'Jetta',
    year: '2021',
    type: 'Sedan grande',
    engine: '2.0',
    size: '5',
  },
  {
    image: 'Imagem 23.png',
    name: 'Saveiro',
    year: '2018',
    type: 'Picape leve-média',
    engine: '1.6',
    size: '5',
  },
  {
    image: 'Imagem 22.png',
    name: 'Strada',
    year: '2016',
    type: 'Picape leve',
    engine: '1.4',
    size: '2',
  },
  {
    image: 'Imagem 20.png',
    name: 'Camaro',
    year: '2017',
    type: 'Coupé',
    engine: '2.0',
    size: '4',
  },
  {
    image: 'Imagem 19.png',
    name: 'T-Cross',
    year: '2020',
    type: 'Crossover',
    engine: '1.6',
    size: '5',
  },
  {
    image: 'Imagem 18.png',
    name: 'Tiggo 8',
    year: '2021',
    type: 'SUV Grande',
    engine: '2.0',
    size: '7',
  },
];
