export const locations = [
  { text: 'Agência Barra Funda - SP', value: 'Agência Barra Funda - SP' },
  { text: 'Agência Copacabana - RJ', value: 'Agência Copacabana - RJ' },
  { text: 'Agência Centro - BH', value: 'Agência Centro - BH' },
  { text: 'Agência Boa Viagem - PE', value: 'Agência Boa Viagem - PE' },
  { text: 'Agência Setor Sul - GO', value: 'Agência Setor Sul - GO' },
  { text: 'Agência Pituba - BA', value: 'Agência Pituba - BA' },
  { text: 'Agência Vila Mariana - SP', value: 'Agência Vila Mariana - SP' },
  { text: 'Agência Jardim Oceânico - RJ', value: 'Agência Jardim Oceânico - RJ' },
  { text: 'Agência Meireles - CE', value: 'Agência Meireles - CE' },
  { text: 'Agência Ponta Verde - AL', value: 'Agência Ponta Verde - AL' },
  { text: 'Agência Centro Histórico - RS', value: 'Agência Centro Histórico - RS' },
  { text: 'Agência Asa Norte - DF', value: 'Agência Asa Norte - DF' },
  { text: 'Agência Pampulha - MG', value: 'Agência Pampulha - MG' },
  { text: 'Agência Ribeirão Preto - SP', value: 'Agência Ribeirão Preto - SP' },
  { text: 'Agência Vitória - ES', value: 'Agência Vitória - ES' },
  { text: 'Agência Florianópolis - SC', value: 'Agência Florianópolis - SC' },
  { text: 'Agência Curitiba Centro - PR', value: 'Agência Curitiba Centro - PR' },
  { text: 'Agência Manaíra - PB', value: 'Agência Manaíra - PB' },
  { text: 'Agência Centro - MA', value: 'Agência Centro - MA' },
  { text: 'Agência Campina Grande - PB', value: 'Agência Campina Grande - PB' },
];